const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const docx = path.join(__dirname, '..', 'LCJ_Terms_and_Policies.docx')
const tmp = path.join(__dirname, '..', '.tmp_terms')
fs.mkdirSync(tmp, { recursive: true })
const zipCopy = path.join(tmp, 'terms.zip')
fs.copyFileSync(docx, zipCopy)
execSync(`powershell -NoProfile -Command "Expand-Archive -Path '${zipCopy.replace(/'/g, "''")}' -DestinationPath '${tmp.replace(/'/g, "''")}' -Force"`, { stdio: 'inherit' })
const xml = fs.readFileSync(path.join(tmp, 'word', 'document.xml'), 'utf8')
const text = xml
  .replace(/<w:tab[^/]*\/>/g, '\t')
  .replace(/<\/w:p>/g, '\n')
  .replace(/<[^>]+>/g, '')
  .replace(/&amp;/g, '&')
  .replace(/&lt;/g, '<')
  .replace(/&gt;/g, '>')
  .replace(/\n{3,}/g, '\n\n')
  .trim()
console.log(text.substring(0, 20000))
